version: '3.8'

services:
  calculater:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - calculater_data:/app/data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  calculater_data:
